# Generated by Django 4.2.25 on 2025-10-06 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("points", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique trash entry identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, help_text="Deletion timestamp"),
                ),
                (
                    "permanent_deletion_at",
                    models.DateTimeField(
                        db_index=True, help_text="Auto-calculated: deleted_at + 30 days"
                    ),
                ),
                (
                    "original_is_public",
                    models.BooleanField(
                        default=False, help_text="Original public status (for restoration)"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        help_text="User who deleted the point",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gps_point",
                    models.OneToOneField(
                        help_text="Trashed GPS point (one-to-one relationship)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash_entry",
                        to="points.gpspoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trash Item",
                "verbose_name_plural": "Trash Items",
                "db_table": "trash",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(
                        fields=["permanent_deletion_at"], name="idx_trash_permanent_deletion"
                    ),
                    models.Index(fields=["deleted_by"], name="idx_trash_deleted_by"),
                    models.Index(fields=["-deleted_at"], name="idx_trash_deleted_at"),
                ],
            },
        ),
    ]
