# Generated by Django 4.2.25 on 2025-10-13 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0003_alter_annotation_options_annotation_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationTrash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique trash entry identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, help_text="Deletion timestamp"),
                ),
                (
                    "permanent_deletion_at",
                    models.DateTimeField(
                        db_index=True, help_text="Auto-calculated: deleted_at + 30 days"
                    ),
                ),
                (
                    "annotation",
                    models.OneToOneField(
                        help_text="Trashed annotation (one-to-one relationship)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash_entry",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        help_text="User who deleted the annotation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation Trash Item",
                "verbose_name_plural": "Annotation Trash Items",
                "db_table": "annotation_trash",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(fields=["permanent_deletion_at"], name="idx_annot_trash_perm_del"),
                    models.Index(fields=["deleted_by"], name="idx_annot_trash_deleted_by"),
                    models.Index(fields=["-deleted_at"], name="idx_annot_trash_deleted_at"),
                ],
            },
        ),
    ]
