# Generated by Django 4.2.25 on 2025-10-06 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("points", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique share identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Recipient email (may not be registered yet)",
                        max_length=254,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[("view", "View"), ("edit", "Edit"), ("transfer", "Transfer")],
                        db_index=True,
                        default="view",
                        help_text="Permission level (view/edit/transfer)",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Token for email invitation link",
                        unique=True,
                    ),
                ),
                (
                    "invitation_sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Invitation email sent timestamp"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="Invitation acceptance timestamp", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Share is active (false when point trashed)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Share creation timestamp"),
                ),
                (
                    "gps_point",
                    models.ForeignKey(
                        help_text="Shared GPS point",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="points.gpspoint",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Point owner (who created the share)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recipient user (set when invitation accepted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
                "db_table": "shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["gps_point"], name="idx_share_point"),
                    models.Index(fields=["recipient_email"], name="idx_share_recipient_email"),
                    models.Index(fields=["recipient_user"], name="idx_share_recipient_user"),
                    models.Index(fields=["invitation_token"], name="idx_share_token"),
                    models.Index(fields=["is_active"], name="idx_share_active"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                fields=("gps_point", "recipient_email"), name="unique_share_per_point_email"
            ),
        ),
    ]
