# Generated by Django 4.2.26 on 2025-11-20 12:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing", "0004_add_autosharerule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="permission_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("manage", "Manage")],
                db_index=True,
                default="view",
                help_text="Permission level (view/edit/manage)",
                max_length=20,
            ),
        ),
    ]
