"""
Serializers for sharing app.

Handles point sharing, permissions, and email invitations.
"""

from datetime import timedelta

from django.utils import timezone
from rest_framework import serializers

from apps.authentication.serializers import UserSerializer
from apps.points.serializers import GPSPointListSerializer
from apps.points.serializers import GPSPointSerializer
from apps.sharing.models import Friendship
from apps.sharing.models import Share


class ShareSerializer(serializers.ModelSerializer):
    """
    Share serializer with full details.

    Includes nested owner, recipient, point, and invitation status.
    Matches OpenAPI schema: Share
    """

    owner = UserSerializer(read_only=True)
    recipient_user = UserSerializer(read_only=True)
    gps_point = GPSPointListSerializer(read_only=True)
    invitation_status = serializers.SerializerMethodField()

    class Meta:
        model = Share
        fields = [
            "id",
            "gps_point",
            "owner",
            "recipient_email",
            "recipient_user",
            "permission_level",
            "invitation_token",
            "invitation_sent_at",
            "accepted_at",
            "invitation_status",
            "is_active",
            "created_at",
        ]
        read_only_fields = [
            "id",
            "owner",
            "recipient_user",
            "invitation_token",
            "invitation_sent_at",
            "accepted_at",
            "invitation_status",
            "is_active",
            "created_at",
        ]

    def get_invitation_status(self, obj):
        """
        Get invitation status: pending, accepted, or expired.
        """
        if obj.accepted_at:
            return "accepted"

        # Check if invitation expired (7 days)
        if obj.invitation_sent_at:
            expiry = obj.invitation_sent_at + timedelta(days=7)
            if timezone.now() > expiry:
                return "expired"

        return "pending"


class CreateShareSerializer(serializers.ModelSerializer):
    """
    Create share serializer.

    Accepts recipient email and permission level, sends invitation.
    Matches OpenAPI schema: CreateShareRequest
    """

    class Meta:
        model = Share
        fields = ["recipient_email", "permission_level"]

    def validate_permission_level(self, value):
        """Validate permission level is valid."""
        if value not in ["view", "edit", "transfer"]:
            raise serializers.ValidationError(
                f"Invalid permission level: {value}. Must be one of: view, edit, transfer"
            )
        return value

    def validate(self, attrs):
        """
        Validate share creation:
        - User must have transfer permission
        - Cannot share with self
        - No duplicate shares for same email

        Note: gps_point comes from view context, not from request data
        """
        user = self.context["request"].user
        gps_point = self.context.get("gps_point")
        if not gps_point:
            raise serializers.ValidationError(
                {
                    "error": "MISSING_POINT",
                    "gps_point": "GPS point is required.",
                }
            )

        recipient_email = attrs["recipient_email"]

        # Check if user has transfer permission
        point_serializer = GPSPointSerializer(gps_point, context=self.context)
        permission = point_serializer.get_permission(gps_point)

        if permission not in ["transfer", "owner"]:
            raise serializers.ValidationError(
                {
                    "error": "ACCESS_DENIED",
                    "owner": "You do not have permission to share this point.",
                }
            )

        # Cannot share with self
        if recipient_email == user.email:
            raise serializers.ValidationError(
                {
                    "error": "SELF_SHARE",
                    "recipient_email": "Cannot share point with yourself.",
                }
            )

        # Check for existing share
        existing_share = Share.objects.filter(
            gps_point=gps_point,
            recipient_email=recipient_email,
        ).first()

        if existing_share:
            raise serializers.ValidationError(
                {
                    "error": "DUPLICATE_SHARE",
                    "recipient_email": f"Point already shared with {recipient_email}.",
                }
            )

        return attrs

    def create(self, validated_data):
        """
        Create share and send invitation email.
        """
        # Set owner from request user (original owner, not sharer) and gps_point from context
        gps_point = self.context["gps_point"]
        validated_data["gps_point"] = gps_point
        validated_data["owner"] = gps_point.owner

        # Generate invitation token (UUID auto-generated by model)
        share = super().create(validated_data)

        # TODO: Send invitation email via email service
        # For now, just mark as sent
        share.invitation_sent_at = timezone.now()
        share.save()

        return share


class UpdateShareSerializer(serializers.ModelSerializer):
    """
    Update share serializer.

    Allows permission level changes only.
    Matches OpenAPI schema: UpdateShareRequest
    """

    class Meta:
        model = Share
        fields = ["permission_level"]

    def validate_permission_level(self, value):
        """Validate permission level is valid."""
        if value not in ["view", "edit", "transfer"]:
            raise serializers.ValidationError(
                f"Invalid permission level: {value}. Must be one of: view, edit, transfer"
            )
        return value

    def validate(self, attrs):
        """Validate user has permission to update share."""
        share = self.instance

        # Only owner or users with transfer permission can update
        point_serializer = GPSPointSerializer(share.gps_point, context=self.context)
        permission = point_serializer.get_permission(share.gps_point)

        if permission not in ["transfer", "owner"]:
            raise serializers.ValidationError(
                {
                    "error": "ACCESS_DENIED",
                    "message": "You do not have permission to update this share.",
                }
            )

        return attrs


class AcceptShareSerializer(serializers.Serializer):
    """
    Accept share invitation serializer.

    Validates invitation token and links share to user.
    Matches OpenAPI schema: AcceptShareRequest
    """

    invitation_token = serializers.UUIDField()

    def validate_invitation_token(self, value):
        """
        Validate invitation token exists and is not expired.
        """
        try:
            share = Share.objects.get(invitation_token=value)
        except Share.DoesNotExist:
            raise serializers.ValidationError(
                {
                    "error": "INVALID_TOKEN",
                    "message": "Invalid invitation token.",
                }
            ) from None

        # Check if already accepted
        if share.accepted_at:
            raise serializers.ValidationError(
                {
                    "error": "ALREADY_ACCEPTED",
                    "message": "Invitation already accepted.",
                }
            )

        # Check if expired (7 days)
        if share.invitation_sent_at:
            expiry = share.invitation_sent_at + timedelta(days=7)
            if timezone.now() > expiry:
                raise serializers.ValidationError(
                    {
                        "error": "INVITATION_EXPIRED",
                        "message": "Invitation has expired (7 days).",
                    }
                )

        self.context["share"] = share
        return value

    def save(self):
        """
        Accept invitation: link share to user and mark accepted.
        """
        share = self.context["share"]
        user = self.context["request"].user

        share.accept(user)
        return share


class FriendSerializer(serializers.Serializer):
    """
    Friend serializer with share statistics.

    Returns friend user details along with counts of shares sent/received.
    Used in friends list view.
    Note: Email is excluded for privacy.
    """

    id = serializers.UUIDField(read_only=True)
    friendship_id = serializers.SerializerMethodField()
    username = serializers.CharField(read_only=True)
    shares_sent_count = serializers.IntegerField(read_only=True, default=0)
    shares_received_count = serializers.IntegerField(read_only=True, default=0)
    friendship_created_at = serializers.SerializerMethodField()

    def get_friendship_id(self, obj):
        """Get the friendship ID."""
        user = self.context.get("request").user
        friendship = Friendship.objects.filter(user=user, friend=obj).first()
        return friendship.id if friendship else None

    def get_friendship_created_at(self, obj):
        """Get the friendship creation timestamp."""
        user = self.context.get("request").user
        friendship = Friendship.objects.filter(user=user, friend=obj).first()
        return friendship.created_at if friendship else None


class AddFriendSerializer(serializers.Serializer):
    """
    Add friend serializer.

    Accepts username of the friend to add.
    """

    username = serializers.CharField(
        required=True,
        help_text="Username of the friend to add",
        max_length=150,
    )

    def validate_username(self, value):
        """Validate username format and existence."""
        if not value or not value.strip():
            raise serializers.ValidationError("Username is required")

        value = value.strip()

        # Check if trying to add self
        user = self.context["request"].user
        if user.username == value:
            raise serializers.ValidationError("Cannot add yourself as a friend")

        # Check if user exists
        from apps.authentication.models import User

        try:
            User.objects.get(username=value)
        except User.DoesNotExist:
            raise serializers.ValidationError(
                f"User with username '{value}' not found"
            ) from None

        return value

    def create(self, validated_data):
        """Create friendship using FriendshipService."""
        from apps.sharing.services import FriendshipService

        user = self.context["request"].user
        username = validated_data["username"]

        try:
            friendship = FriendshipService.add_friend(user, username)
            return friendship
        except ValueError as e:
            raise serializers.ValidationError({"username": str(e)}) from None


class FriendshipSerializer(serializers.ModelSerializer):
    """
    Friendship serializer.

    Returns friendship details including friend info.
    """

    friend = UserSerializer(read_only=True)

    class Meta:
        model = Friendship
        fields = ["id", "friend", "created_at"]
        read_only_fields = ["id", "friend", "created_at"]


class SharedPointWithPermissionSerializer(serializers.Serializer):
    """
    Serializer for points with share information.

    Includes both point data and the associated share's permission level and ID.
    """
    id = serializers.UUIDField(read_only=True)
    title = serializers.CharField(read_only=True)
    latitude = serializers.FloatField(read_only=True)
    longitude = serializers.FloatField(read_only=True)
    type = PointTypeSerializer(read_only=True)
    tags = TagSerializer(many=True, read_only=True)
    created_at = serializers.DateTimeField(read_only=True)
    share_id = serializers.SerializerMethodField()
    permission_level = serializers.SerializerMethodField()

    def get_share_id(self, obj):
        """Get the share ID for this point."""
        return getattr(obj, 'share_id', None)

    def get_permission_level(self, obj):
        """Get the permission level for this point."""
        return getattr(obj, 'permission_level', None)


class FriendDetailSerializer(serializers.Serializer):
    """
    Friend detail serializer with shared points.

    Returns friend details and list of points shared with them.
    Note: Email is excluded for privacy.
    """

    id = serializers.UUIDField(read_only=True)
    username = serializers.CharField(read_only=True)
    friendship_created_at = serializers.DateTimeField(read_only=True)
    shared_points = SharedPointWithPermissionSerializer(many=True, read_only=True)
    shares_sent_count = serializers.IntegerField(read_only=True)
    shares_received_count = serializers.IntegerField(read_only=True)


class BatchShareSerializer(serializers.Serializer):
    """
    Batch share serializer.

    Accepts multiple point IDs and usernames to create shares in bulk.
    """

    point_ids = serializers.ListField(
        child=serializers.UUIDField(),
        required=True,
        help_text="List of GPS point UUIDs to share",
        min_length=1,
    )

    usernames = serializers.ListField(
        child=serializers.CharField(max_length=150),
        required=True,
        help_text="List of usernames to share with",
        min_length=1,
    )

    permission_level = serializers.ChoiceField(
        choices=["view", "edit", "transfer"],
        required=True,
        help_text="Permission level for all shares",
    )

    def validate_point_ids(self, value):
        """Validate point IDs list."""
        if not value:
            raise serializers.ValidationError("At least one point ID is required")

        if len(value) > 100:
            raise serializers.ValidationError("Cannot share more than 100 points at once")

        return value

    def validate_usernames(self, value):
        """Validate usernames list."""
        if not value:
            raise serializers.ValidationError("At least one username is required")

        if len(value) > 50:
            raise serializers.ValidationError("Cannot share with more than 50 users at once")

        # Remove duplicates and whitespace
        cleaned = [u.strip() for u in value if u.strip()]
        return list(set(cleaned))

    def create(self, validated_data):
        """Create batch shares using BatchShareService."""
        from apps.sharing.services import BatchShareService

        user = self.context["request"].user
        point_ids = [str(pid) for pid in validated_data["point_ids"]]
        usernames = validated_data["usernames"]
        permission_level = validated_data["permission_level"]

        result = BatchShareService.batch_create_shares(
            point_ids=point_ids,
            usernames=usernames,
            permission_level=permission_level,
            owner=user,
        )

        return result
