# Generated by Django 4.2.25 on 2025-10-06 22:59

import apps.annotations.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique annotation identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("file", "File"),
                        ],
                        db_index=True,
                        help_text="Annotation type (text/image/document/file)",
                        max_length=20,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, help_text="Rich text HTML (only for text type)", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="File upload (only for non-text types)",
                        max_length=500,
                        null=True,
                        upload_to=apps.annotations.models.annotation_file_path,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0,
                        help_text="File size in bytes (max 1GB)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1073741824),
                        ],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, help_text="MIME type (e.g., image/jpeg)", max_length=100
                    ),
                ),
                (
                    "can_preview",
                    models.BooleanField(
                        default=False, help_text="Preview supported (images and PDFs)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Upload/creation timestamp"),
                ),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
                "db_table": "annotations",
                "ordering": ["-created_at"],
            },
        ),
    ]
