# Generated by Django 4.2.25 on 2025-10-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("points", "0001_initial"),
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="gps_point",
            field=models.ForeignKey(
                help_text="Associated GPS point",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="points.gpspoint",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["gps_point"], name="idx_annotation_point"),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["type"], name="idx_annotation_type"),
        ),
    ]
