# Generated by Django 4.2.25 on 2025-10-13 12:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
        migrations.AddField(
            model_name="annotation",
            name="order",
            field=models.IntegerField(
                db_index=True, default=0, help_text="Display order (lower values first)"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["gps_point", "order"], name="idx_annotation_point_order"),
        ),
    ]
