# Generated by Django 4.2.25 on 2025-10-06 22:59

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique point identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Point title (required)", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Rich text HTML description with emoticons", null=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Geographic coordinates (longitude, latitude)",
                        srid=4326,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Public visibility (accessible to all users)"
                    ),
                ),
                (
                    "editing_lock_acquired_at",
                    models.DateTimeField(
                        blank=True, help_text="Lock acquisition timestamp", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
            ],
            options={
                "verbose_name": "GPS Point",
                "verbose_name_plural": "GPS Points",
                "db_table": "gps_points",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique tag identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (alphanumeric, hyphens, underscores only)",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Tag creation timestamp"),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="idx_tag_name")],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_tag_name_case_insensitive",
            ),
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="editing_lock_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently editing (null if unlocked)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="owner",
            field=models.ForeignKey(
                help_text="Point owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Categorization tags", related_name="points", to="points.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="gpspoint",
            index=models.Index(fields=["owner"], name="idx_point_owner"),
        ),
        migrations.AddIndex(
            model_name="gpspoint",
            index=models.Index(fields=["is_public"], name="idx_point_public"),
        ),
        migrations.AddIndex(
            model_name="gpspoint",
            index=models.Index(fields=["owner", "-created_at"], name="idx_point_owner_timeline"),
        ),
    ]
