# Generated by Django 4.2.25 on 2025-10-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique point type identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type name (must be unique per user)", max_length=100
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="/icons/default.svg",
                        help_text="Icon URL or asset reference",
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order (lower values first)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        default="active",
                        help_text="Type status (active or soft-deleted)",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type owner (null for base/system types)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Type",
                "verbose_name_plural": "Point Types",
                "db_table": "point_types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="Point type (defaults to base 'Point' type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="points.pointtype",
            ),
        ),
        migrations.AddIndex(
            model_name="pointtype",
            index=models.Index(fields=["user", "order"], name="idx_pointtype_user_order"),
        ),
        migrations.AddIndex(
            model_name="pointtype",
            index=models.Index(fields=["user", "status"], name="idx_pointtype_user_status"),
        ),
        migrations.AddConstraint(
            model_name="pointtype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_pointtype_name_per_user",
                violation_error_message="Type name must be unique per user",
            ),
        ),
    ]
