# Generated by Django 4.2.25 on 2025-10-17 07:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("points", "0002_add_point_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTypeOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order for this user (lower values first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        help_text="The point type being ordered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_orders",
                        to="points.pointtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who customized the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Type Order",
                "verbose_name_plural": "User Type Orders",
                "db_table": "user_type_orders",
                "ordering": ["order"],
                "indexes": [
                    models.Index(fields=["user", "order"], name="idx_userorder_user_order")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usertypeorder",
            constraint=models.UniqueConstraint(
                fields=("user", "type"),
                name="unique_user_type_order",
                violation_error_message="Each user can only have one order value per type",
            ),
        ),
    ]
