# Generated by Django 4.2.25 on 2025-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0005_multilingual_point_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointtype",
            name="icon",
            field=models.TextField(
                default="📍", help_text="Icon URL, emoji, data URI, or asset reference"
            ),
        ),
    ]
