# Generated by Django 4.2.25 on 2025-10-23 22:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0006_alter_pointtype_icon"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pointtype",
            constraint=models.UniqueConstraint(
                fields=("owner", "names"), name="unique_pointtype_name_per_user"
            ),
        ),
    ]
