# Generated by Django 4.2.27 on 2025-12-17 19:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0008_add_owner_to_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name (max 50 characters, case-insensitive uniqueness)", max_length=50
            ),
        ),
    ]
