# Generated by Django 4.2.26 on 2025-11-12 21:11

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique user identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="User's pseudonym (used for login)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA-256 hash of lowercase email for uniqueness enforcement",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    fernet_fields.fields.EncryptedEmailField(
                        help_text="User email address (encrypted at rest, required for account recovery)",
                        max_length=255,
                    ),
                ),
                (
                    "storage_used",
                    models.BigIntegerField(
                        default=0,
                        help_text="Bytes used by user's annotation files",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "storage_limit",
                    models.BigIntegerField(
                        default=2147483648,
                        help_text="Maximum bytes allowed (default 2GB)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Indicates whether the user's email is verified."
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, help_text="Code used for email verification.", max_length=6
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp, NULL for active users",
                        null=True,
                    ),
                ),
                (
                    "pending_email",
                    fernet_fields.fields.EncryptedEmailField(
                        blank=True,
                        help_text="Temporary storage for unconfirmed email changes",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="EmailChangeConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "new_email",
                    fernet_fields.fields.EncryptedEmailField(
                        help_text="Requested new email address (encrypted)", max_length=255
                    ),
                ),
                (
                    "new_email_hash",
                    models.CharField(
                        help_text="SHA-256 hash of new email for uniqueness check before confirmation",
                        max_length=64,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="HMAC-based confirmation token", max_length=128, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Token creation timestamp"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration timestamp (created_at + 30 minutes)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when confirmed, NULL if pending", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting email change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Change Confirmation",
                "verbose_name_plural": "Email Change Confirmations",
                "db_table": "email_change_confirmations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("PSEUDONYM_CHANGED", "Pseudonym Changed"),
                            ("EMAIL_CHANGED", "Email Changed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("ACCOUNT_DELETED", "Account Deleted"),
                            ("EMAIL_CHANGE_REQUESTED", "Email Change Requested"),
                            ("EMAIL_CHANGE_CONFIRMED", "Email Change Confirmed"),
                        ],
                        help_text="Type of account operation",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Client user agent", max_length=256, null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="When operation occurred"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, help_text="Additional operation-specific data", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose account was modified",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Log",
                "verbose_name_plural": "Account Logs",
                "db_table": "account_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="idx_user_username"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email_hash"], name="idx_user_email_hash"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="idx_user_active"),
        ),
    ]
