# Generated by Django 4.2.25 on 2025-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the user's email is verified."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank=True, help_text="Code used for email verification.", max_length=6
            ),
        ),
    ]
