# Generated by Django 4.2.26 on 2025-11-14 16:03

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_consolidate_email_confirmations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmation",
            name="expires_at",
            field=models.DateTimeField(help_text="Token expiration timestamp"),
        ),
        migrations.CreateModel(
            name="EmailChangeConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "new_email",
                    fernet_fields.fields.EncryptedEmailField(
                        help_text="Requested new email address (encrypted)", max_length=255
                    ),
                ),
                (
                    "new_email_hash",
                    models.CharField(
                        help_text="SHA-256 hash of new email for uniqueness check before confirmation",
                        max_length=64,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="HMAC-based confirmation token", max_length=128, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Token creation timestamp"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration timestamp (created_at + 30 minutes)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when confirmed, NULL if pending", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting email change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Change Confirmation",
                "verbose_name_plural": "Email Change Confirmations",
                "db_table": "email_change_confirmations",
                "ordering": ["-created_at"],
            },
        ),
    ]
