# Generated by Django 4.2.27 on 2025-12-17 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_emailconfirmation_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("USERNAME_CHANGED", "Username Changed"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_CONFIRMED", "Password Reset Confirmed"),
                    ("ACCOUNT_DELETED", "Account Deleted"),
                    ("EMAIL_CHANGE_REQUESTED", "Email Change Requested"),
                    ("EMAIL_CHANGE_CONFIRMED", "Email Change Confirmed"),
                    ("EMAIL_CONFIRMED", "Email Confirmed"),
                    ("CONFIRMATION_EMAIL_RESENT", "Confirmation Email Resent"),
                ],
                help_text="Type of account operation",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="HMAC-based reset token", max_length=128, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Token creation timestamp"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration timestamp (created_at + 24 hours)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when confirmed, NULL if pending", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request (for security audit)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "db_table": "password_resets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_pwd_reset_user"),
                    models.Index(fields=["token"], name="idx_pwd_reset_token"),
                ],
            },
        ),
    ]
