# Generated by Django 4.2.25 on 2025-10-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "language",
                    models.CharField(choices=[("en", "English")], default="en", max_length=10),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("auto", "Auto"), ("light", "Light"), ("dark", "Dark")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("geojson", "GeoJSON"), ("kml", "KML"), ("csv", "CSV")],
                        default="geojson",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
    ]
