# Generated by Django 4.2.25 on 2025-10-18 23:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")], default="en", max_length=10
            ),
        ),
    ]
