# Generated by Django 4.2.25 on 2025-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_add_french_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="default_map_type",
            field=models.CharField(
                choices=[
                    ("osm", "Street Map"),
                    ("satellite", "Satellite"),
                    ("topo", "Topographic"),
                    ("cycle", "Cycle Map"),
                ],
                default="osm",
                max_length=20,
            ),
        ),
    ]
