# Generated by Django 4.2.25 on 2025-12-11 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_userpreferences_default_map_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="export_format",
        ),
    ]
